//
//  TBPost.m
//  Tribo
//
//  Created by Carter Allen on 9/25/11.
//  Copyright (c) 2012 The Tribo Authors.
//  See the included License.md file.
//

#import "TBPost.h"
#import "markdown.h"
#import "html.h"
#import "TBError.h"
#import "NSDateFormatter+TBAdditions.h"

@interface TBPost ()
- (BOOL)parse:(NSError **)error;
- (NSError *)badPostError;
@end

@implementation TBPost
@synthesize URL=_URL;
@synthesize title=_title;
@synthesize author=_author;
@synthesize date=_date;
@synthesize slug=_slug;
@synthesize markdownContent=_markdownContent;

+ (TBPost *)postWithURL:(NSURL *)URL error:(NSError **)error{
	return (TBPost *)[super pageWithURL:URL inSite:nil error:error];
}

- (BOOL)parse:(NSError **)error {
	NSMutableString *markdownContent = [NSMutableString stringWithContentsOfURL:self.URL encoding:NSUTF8StringEncoding error:nil];
    if (![markdownContent length]) {
        if (error) {
            *error = [self badPostError];
        }
        return NO;
    }
	
	// Titles are optional.
	// A single # header on the first line of the document is regarded as the title.
	static NSRegularExpression *headerRegex;
	if (headerRegex == nil)
		headerRegex = [NSRegularExpression regularExpressionWithPattern:@"#[ \\t](.*)[ \\t]#" options:0 error:nil];
	NSRange firstLineRange = NSMakeRange(0, [markdownContent rangeOfCharacterFromSet:[NSCharacterSet newlineCharacterSet]].location);
	NSString *firstLine = [markdownContent substringWithRange:firstLineRange];
	NSTextCheckingResult *titleResult = [headerRegex firstMatchInString:firstLine options:0 range:NSMakeRange(0, firstLine.length)];
	if (titleResult) {
		self.title = [firstLine substringWithRange:[titleResult rangeAtIndex:1]];
		[markdownContent deleteCharactersInRange:NSMakeRange(firstLineRange.location, firstLineRange.length + 1)];
	}
	[markdownContent deleteCharactersInRange:[markdownContent rangeOfCharacterFromSet:[NSCharacterSet newlineCharacterSet]]];
	self.markdownContent = markdownContent;
	
	// Dates are generated by a pattern in the post file name.
	static NSRegularExpression *fileNameRegex;
	if (fileNameRegex == nil)
		fileNameRegex = [NSRegularExpression regularExpressionWithPattern:@"^(\\d+-\\d+-\\d+)-(.*)" options:0 error:nil];
	NSString *fileName = [self.URL.lastPathComponent stringByDeletingPathExtension];
	NSTextCheckingResult *fileNameResult = [fileNameRegex firstMatchInString:fileName options:0 range:NSMakeRange(0, fileName.length)];
	if (fileNameResult) {
		NSDateFormatter *fileNameDateFormatter = [NSDateFormatter tb_cachedDateFormatterFromString:@"yyyy-MM-dd"];
		self.date = [fileNameDateFormatter dateFromString:[fileName substringWithRange:[fileNameResult rangeAtIndex:1]]];
		self.slug = [fileName substringWithRange:[fileNameResult rangeAtIndex:2]];
	}
	
	// Create and fill a buffer for with the raw markdown data.
	if ([markdownContent length] == 0) return YES;
	struct sd_callbacks callbacks;
	struct html_renderopt options;
	const char *rawMarkdown = [markdownContent cStringUsingEncoding:NSUTF8StringEncoding];
	struct buf *smartyPantsOutputBuffer = bufnew(1);
	sdhtml_smartypants(smartyPantsOutputBuffer, (const unsigned char *)rawMarkdown, strlen(rawMarkdown));
	//struct buf *inputBuffer = bufnew(strlen(rawMarkdown));
	//bufputs(inputBuffer, rawMarkdown);
	
	// Parse the markdown into a new buffer using Sundown.
	struct buf *outputBuffer = bufnew(64);
	sdhtml_renderer(&callbacks, &options, 0);
	struct sd_markdown *markdown = sd_markdown_new(0, 16, &callbacks, &options);
	sd_markdown_render(outputBuffer, smartyPantsOutputBuffer->data, smartyPantsOutputBuffer->size, markdown);
	sd_markdown_free(markdown);
	
	self.content = @(bufcstr(outputBuffer));
	
	bufrelease(smartyPantsOutputBuffer);
	bufrelease(outputBuffer);
    return YES;
}
- (NSError *)badPostError{
    NSDictionary *info = @{NSLocalizedDescriptionKey: [NSString stringWithFormat:@"Could not read any content from the post at %@", [[self URL] lastPathComponent]], NSURLErrorKey: [self URL]};
    NSError *contentError = [NSError errorWithDomain:TBErrorDomain code:TBErrorBadContent userInfo:info];
    return contentError;
}
@end
